import tqdm
from colorama import Fore

def Reset() -> None:
    ...

class ColoredTqdm(tqdm.tqdm):
    color2: str

    def __init__(self, iterable = ..., desc=..., total=..., leave=..., file=...,
                 ncols=..., mininterval=..., maxinterval=..., miniters=...,
                 ascii=..., disable=..., unit=..., unit_scale=...,
                 dynamic_ncols=..., smoothing=..., bar_format=..., initial=...,
                 position=..., postfix=..., unit_divisor=..., write_bytes=...,
                 lock_args=..., nrows=..., colour=..., delay=..., gui=...,
                 color1: str = ..., color2: str = ...,
                 **kwargs):
        ...
    def close(self):
        ...

def ForeBlack(*args, sep:str = ...) -> str:
    ...

def ForeRed(*args, sep:str = ...) -> str:
    ...

def ForeGreen(*args, sep:str = ...) -> str:
    ...

def ForeYellow(*args, sep:str = ...) -> str:
    ...

def ForeBlue(*args, sep:str = ...) -> str:
    ...

def ForeMagenta(*args, sep:str = ...) -> str:
    ...

def ForeCyan(*args, sep:str = ...) -> str:
    ...

def ForeWhite(*args, sep:str = ...) -> str:
    ...

def ForeLightBlack(*args, sep:str = ...) -> str:
    ...

def ForeLightRed(*args, sep:str = ...) -> str:
    ...

def ForeLightGreen(*args, sep:str = ...) -> str:
    ...

def ForeLightYellow(*args, sep:str = ...) -> str:
    ...

def ForeLightBlue(*args, sep:str = ...) -> str:
    ...

def ForeLightMagenta(*args, sep:str = ...) -> str:
    ...

def ForeLightCyan(*args, sep:str = ...) -> str:
    ...

def ForeLightWhite(*args, sep:str = ...) -> str:
    ...

def StartBlack() -> None:
    ...

def StartRed() -> None:
    ...

def StartGreen() -> None:
    ...

def StartYellow() -> None:
    ...

def StartBlue() -> None:
    ...

def StartMagenta() -> None:
    ...

def StartCyan() -> None:
    ...

def StartWhite() -> None:
    ...

def StartLightBlack() -> None:
    ...

def StartLightRed() -> None:
    ...

def StartLightGreen() -> None:
    ...

def StartLightYellow() -> None:
    ...

def StartLightBlue() -> None:
    ...

def StartLightMagenta() -> None:
    ...

def StartLightCyan() -> None:
    ...

def StartLightWhite() -> None:
    ...
