# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 5. 第四步：执行打包命令
    - name: Build package
      run: python -m build

    # 6. 第六步：检查软件包是否正确构建
    - name: Check package
      run: twine check dist/*

    # 7. 第七步：保存打包结果（这是关键！）
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ScratchAnalyzer-${{ matrix.python-version }}
        path: dist/
